{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
type: Opaque
stringData:
  MONGO_URL: "{{ .Values.secret.MONGODB_URI }}"
{{- end }}
